/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/25/2012 04:15:00
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{

  /*
   * This is a server only script. Hence no URL is required.
   * Standlone monitoring script 
   * -Ankur Srivastava
   */
}
