/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 05/22/2012 11:54:50
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
        char file_attachment[1024];
        char *fileattachment=NULL;
        strcpy(file_attachment, ns_eval_string("{Attachment}"));
        fileattachment = ns_eval_string(file_attachment);
        ns_smtp_send("send_email_invite",
        "SMTP_SERVER=192.168.1.83:9010",
        "USER_ID=netstorm",
        "PASSWORD=netstorm",
        "FROM_EMAIL=mail@cavisson.com",
        "TO_EMAILS=shakti.jha@cavisson.com",
        "CC_EMAILS=atul@cavisson.com",
        "BCC_EMAILS=arun@cavisson.com",
        "SUBJECT=hi how r u?",
        "BODY=$CAVRANDOM_BYTES$=10,20",
        //"ATTACHMENT=/home/netstorm/smtp_attachment,/home/netstorm/smtp_attachment",
        "MESSAGE_COUNT=1");
        ns_page_think_time(0);

}


