/*-----------------------------------------------------------------------------
    Name:AccountSummary
    Generated By: Govind
    Date of generation: 04/19/2022 01:55:54
    Flow details:
    Build details: 4.8.0 (build# 84)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void AccountSummary()
{
	ns_start_transaction("AccountSummary");
    ns_web_url ("AccountSummary",
        "URL=https://66.220.31.137:8443/AccountService/FetchSummary",
        "METHOD=POST",
        BODY_BEGIN,
            "<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <AccountSummary>
      <REQ_MSG_HEADER_AREA>
      <REQ_LOGIN>David</REQ_LOGIN>
      </REQ_MSG_HEADER_AREA>
      <REQUEST_VAR>
      <REQ_TYPE>AccountSummary</REQ_TYPE>
      <USER_ACCOUNT>David</USER_ACCOUNT>
      </REQUEST_VAR>
    </AccountSummary>
  </soap:Body>
</soap:Envelope>",
        BODY_END
    );

    ns_end_transaction("AccountSummary", NS_AUTO_STATUS);

    ns_page_think_time(10);

}
