/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: Govind
    Date of generation: 04/19/2022 01:55:54
    Flow details:
    Build details: 4.8.0 (build# 84)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int init_script()
{
    return 0;
}
