/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 02/13/2020 02:33:41
    Flow details:
    Build details: 4.1.15 (build# 202)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flowV2()
{
	ns_start_transaction("PFL_ItemAvailability_V2");    
    ns_web_url("EPS_AssociateAccount_V2",
        "URL=http://68.235.60.35:9002/pfl/api/itemAvailability/details",
        "METHOD=POST",        
        "HEADER=Accept:application/json",
        "HEADER=Content-Type:application/json",
        "HEADER=X-PFL-experimentation:V2",
        BODY_BEGIN,
	"{
  "clientXrefDocument" : null,
  "batchCode" : "1",
  "reservationNumber" : "0",
  "sellAssociateNumber" : "01005293",
  "itemList" : [ {
    "resgistryNbr" : null,
    "shipToState" : "VA",
    "shipMethod" : "3",
    "quantityRequested" : "1",
    "countryCode" : "840",
    "unitPrice" : "24.99",
    "requestedOrderMethod" : "MO",
    "filLocationNumber" : null,
    "upcNumber" : "719812261911",
    "itemAppId" : "MCOM",
    "shipToZipCode" : "22102",
    "shipMethodOptions" : "1",
    "lineNumber" : "1",
    "iaType" : "MO",
    "priceFlag" : "true",
    "priceStatus" : null
  }, {
    "resgistryNbr" : null,
    "shipToState" : "VA",
    "shipMethod" : "3",
    "quantityRequested" : "1",
    "countryCode" : "840",
    "unitPrice" : "23.99",
    "requestedOrderMethod" : "MO",
    "filLocationNumber" : "5494",
    "upcNumber" : "719812280813",
    "itemAppId" : "MCOM",
    "shipToZipCode" : "22102",
    "shipMethodOptions" : "9",
    "lineNumber" : "2",
    "iaType" : "MO",
    "priceFlag" : "true",
    "priceStatus" : null
  } ],
  "racfId" : "{RacfID}",
  "requestType" : "R",
  "referenceId" : "271",
  "clientFunctionName" : "GA",
  "orderId" : "186461346",
  "sellLocationNumber" : "139"
}",
        BODY_END
    );
    ns_end_transaction("PFL_ItemAvailability_V2", NS_AUTO_STATUS);    
    ns_page_think_time(0);


}
