/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 01/17/2022 06:57:09
    Flow details:
    Build details: 4.6.1 (build# 91)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_start_transaction ("google");
    ns_web_url ("google",
        "URL=https://www.google.com/"
    );

    ns_end_transaction ("google", NS_AUTO_STATUS);
    ns_page_think_time(0);

}
