/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
    Date of generation: 01/17/2022 12:55:52
    Flow details:
    Build details: 4.6.1 (build# 91)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void HOW_Copy()
{
	
    ns_start_transaction("Login");
    ns_web_url ("Login",
        "URL=https://nspoc3.cav-test.com:9010/login",
        "METHOD=POST",
        "HEADER=Content-Type:application/json",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        BODY_BEGIN,
            "$CAVINCLUDE$=Login.json",
        BODY_END
    );
    ns_end_transaction("Login", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

    ns_start_transaction("Get_Attachment_URL");
    ns_web_url ("Get_Attachment_URL",
        "URL=https://nspoc3.cav-test.com:9010/attachment?ext=png",
        "METHOD=GET",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9"
    );
    ns_end_transaction("Get_Attachment_URL", NS_AUTO_STATUS);


    ns_page_think_time(0.0);


    ns_start_transaction("Upload_Attachment");
    ns_web_url ("Upload_Attachment",
        "URL=https://nspoc3.cav-test.com:9010/",
        //"URL=http://{attachment_url}/",
        "METHOD=POST",
        "HEADER=Content-Type:multipart/form-data; boundary=----WebKitFormBoundary17e86e2cb48",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        MULTIPART_BODY_BEGIN,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"key\""
            BODY_BEGIN,
            "{attachment_key}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"x-amz-algorithm\""
            BODY_BEGIN,
            "{attachment_x-amz-algorithm}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"x-amz-credential\""
            BODY_BEGIN,
            "{attachment_x-amz-credential}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"policy\""
            BODY_BEGIN,
            "{attachment_policy}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"x-amz-signature\""
            BODY_BEGIN,
            "{attachment_x-amz-signature}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"x-amz-date\""
            BODY_BEGIN,
            "{attachment_x-amz-date}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"x-amz-security-token\""
            BODY_BEGIN,
            "{attachment_x-amz-security-token}",
            BODY_END,
            MULTIPART_BOUNDARY,
            "HEADER=Content-Disposition: form-data; name=\"file\"",
            "HEADER=Content-Type: image/jpeg"
            BODY_BEGIN,
            "filename=testimage.jpeg",
            BODY_END,
        MULTIPART_BODY_END,
    );
    ns_end_transaction("Upload_Attachment", NS_AUTO_STATUS);



    ns_page_think_time(0.0);

    ns_start_transaction("Create_Incident");
    ns_web_url ("Create_Incident",
        "URL=https://nspoc3.cav-test.com:9010/incident",
        "METHOD=POST",
        "HEADER=Content-Type:application/json",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        BODY_BEGIN,
            "$CAVINCLUDE$=Create_Incident.json",
        BODY_END
    );
    ns_end_transaction("Create_Incident", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

    ns_start_transaction("Get_Incident_s_");
    ns_web_url ("Get_Incident_s_",
        "URL=https://nspoc3.cav-test.com:9010/incident/INC4100932",
        //"URL=https://nspoc3.cav-test.com:9010/incident/{incident_number}",
        "METHOD=GET",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9"
    );
    ns_end_transaction("Get_Incident_s_", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

    ns_start_transaction("Get_Asset");
    ns_web_url ("Get_Asset",
        "URL=https://nspoc3.cav-test.com:9010/asset/wcw/assets.json",
        "METHOD=GET",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9"
    );
    ns_end_transaction("Get_Asset", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

    ns_start_transaction("Get_Config");
    ns_web_url ("Get_Config",
        "URL=https://nspoc3.cav-test.com:9010/asset/wcw/config.json",
        "METHOD=GET",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9"
    );
    ns_end_transaction("Get_Config", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

}
