/*-----------------------------------------------------------------------------
    Name:CreateIncident
    Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
    Date of generation: 01/17/2022 12:55:52
    Flow details:
    Build details: 4.6.1 (build# 91)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void CreateIncident(){
    ns_start_transaction("Create_Incident");
    ns_web_url ("Create_Incident",
        "URL=https://nspoc3.cav-test.com:9010/incident",
        "METHOD=POST",
        "HEADER=Content-Type:application/json",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        BODY_BEGIN,
            "$CAVINCLUDE$=Create_Incident.json",
        BODY_END
    );
    ns_end_transaction("Create_Incident", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

}
