/*-----------------------------------------------------------------------------
    Name:GetConfig
    Generated By: This is an auto generated script. You can, however, make a copy of this script using advanced script manager and enhance it.
    Date of generation: 01/17/2022 12:55:52
    Flow details:
    Build details: 4.6.1 (build# 91)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void GetConfig(){
    ns_start_transaction("Get_Config");
    ns_web_url ("Get_Config",
        "URL=https://nspoc3.cav-test.com:9010/asset/wcw/config.json",
        "METHOD=GET",
        "HEADER=Authorization:Bearer {token}",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9"
    );
    ns_end_transaction("Get_Config", NS_AUTO_STATUS);


    ns_page_think_time(0.0);

}
