/*-----------------------------------------------------------------------------
    Name: Login
    Generated By: cavisson
    Date of generation: 02/28/2022 07:39:33
    Flow details:
    Build details: 4.8.0 (build# 49)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void Login()
{
	 ns_start_transaction("Login");
    ns_web_url ("Login",
        "URL=https://nspoc3.cav-test.com:9010/login",
        "METHOD=POST",
        "HEADER=Content-Type:application/json",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        BODY_BEGIN,
            "$CAVINCLUDE$=Login.json",
        BODY_END
    );
    ns_end_transaction("Login", NS_AUTO_STATUS);
}