/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: cavisson
    Date of generation: 02/12/2020 02:05:30
    Flow details:
    Build details: 4.1.15 (build# 202)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{
    ns_start_transaction("BalanceEnquiry");    
    ns_web_url("BalanceEnquiry",
        "URL=http://127.0.0.1/AJB/balanceinquiry",
        "METHOD=POST",        
        "HEADER=Accept:application/json",
        "HEADER=Content-Type:application/json",
        BODY_BEGIN,
		"{
            	"RequestType": "ViewBalance",
               "Version": "{Version}",
               "AssociateAccount": [{
                                     	"accId": "{AccountID}",
                                        "encryptedsecuritycode": "{code}",
                                        "phonenum": "{mobno}",
                                        "originator": "national"
              }]
           }",
        BODY_END
        );
    ns_end_transaction("BalanceEnquiry", NS_AUTO_STATUS);    
    ns_page_think_time(0);

}
