nsl_decl_var(attachment_AWSAccessKeyId, DefaultValue=ASIARYBPOXXOZ7JHS5VK);
nsl_decl_var(attachment_signature, DefaultValue=UpRr0yfm/C7GjCV8/8ENUtdk1FI=);
nsl_decl_var(attachment_x-amx-date, DefaultValue=-1);
nsl_decl_var(how_host, DefaultValue=https://ju32bbaprh.execute-api.cn-northwest-1.amazonaws.com.cn);
nsl_json_var(token, PAGE=Login, ORD=1, OBJECT_PATH="root.token", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_url, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.url", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_key, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.key", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_x-amz-algorithm, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.x-amz-algorithm", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_x-amz-credential, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.x-amz-credential", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_x-amz-date, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.x-amz-date", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_x-amz-security-token, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.x-amz-security-token", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_policy, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.policy", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(attachment_x-amz-signature, PAGE=Get_Attachment_URL, ORD=1, OBJECT_PATH="root.fields.x-amz-signature", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
nsl_json_var(incident_number, PAGE=Create_Incident, ORD=1, OBJECT_PATH="root.number", SaveOffset=0, RETAINPREVALUE="YES", EncodeMode=None);
